"""empty message

Revision ID: 44e0a436ca01
Revises: d8da06ec9a2d
Create Date: 2020-01-18 10:19:40.079437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e0a436ca01'
down_revision = 'd8da06ec9a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artist', ['name', 'city', 'state_id', 'phone'])
    op.create_unique_constraint(None, 'venue', ['name', 'city', 'state_id', 'address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'artist', type_='unique')
    # ### end Alembic commands ###
