"""empty message

Revision ID: 7ecbcdc67001
Revises: f445e822c042
Create Date: 2020-01-18 08:56:23.997842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecbcdc67001'
down_revision = 'f445e822c042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('state_id_state_key', 'state', type_='unique')
    op.create_unique_constraint(None, 'state', ['state'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'state', type_='unique')
    op.create_unique_constraint('state_id_state_key', 'state', ['id', 'state'])
    # ### end Alembic commands ###
