"""empty message

Revision ID: d8da06ec9a2d
Revises: 7ecbcdc67001
Create Date: 2020-01-18 09:03:07.166219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8da06ec9a2d'
down_revision = '7ecbcdc67001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genre', ['name'])
    op.create_unique_constraint(None, 'show', ['artist_id', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='unique')
    op.drop_constraint(None, 'genre', type_='unique')
    # ### end Alembic commands ###
